on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -e

            # Step 1: Navigate to the /opt directory
            #cd /opt/apps

            # Step 2: Clone or refresh the latest repository
            if [ -d "tait" ]; then
              echo "Directory already exists. Removing..."
              rm -rf tait
            fi
            mkdir tait
            cd tait

            # Clone the repo using token
            git clone https://devTatendaMarvelous:${{ secrets.TOKEN }}@github.com/devTatendaMarvelous/portfolio .

            git checkout main
            git pull origin main

            # Step 3: Stop, remove, and clean Docker resources
            docker stop tait || true
            docker rm tait || true
            docker rmi tait || true

            # Step 4: Build and run the Docker container
            docker build -t tait .
            docker run -d -p 9001:8080 --name=tait --restart=always tait

            # Step 5: Clean up
            cd ..
            rm -rf tait

            echo "Deployment completed successfully."
          EOF
