on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Connect and Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22 "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" << 'EOF'
          # Step 1: Navigate to the /opt directory
          cd /opt/apps

          # Step 2: Clone the latest repository
          if [ -d "tait" ]; then
            echo "Directory already exists. Removing..."
            rm -rf tait
          fi
          mkdir tait
          # Step 3: Navigate to the project directory
          cd tait
          git clone https://devTatendaMarvelous:${{ secrets.TOKEN }}@github.com/devTatendaMarvelous/portfolio .

          git checkout main
          git pull origin main

          # Step 4: Stop, remove, and clean Docker resources
          docker stop  tait || true
          docker rm  tait || true
          docker rmi  tait || true
          ufw allow 9001

          # Step 5: Build and run the Docker container
          docker build -t  tait .
          docker run -d -p 9001:8080 --name=tait --restart=always  tait

          # Step 6: Clean up cloned repository
          cd ..
          rm -rf tait

          echo "Deployment completed successfully."
          EOF
